# 一、Numpy基础

In [1]:
import numpy as np

## 1、创建ndarray

In [63]:
# 列表进行创建 一维数组
data1 = [1,3,5,2,4]
arr1 = np.array(data1)
# print(arr1)
# print(type(arr1))

# 列表创建二维数组
data2 = [[1,3,5,2,4],[2,5,1,2]]
arr2 = np.array(data1)
# print(arr1)

# 创建全0一维数组
z1 = np.zeros(10)
# print(z1)

# 创建全0二维数组
z2 = np.zeros((2,2))
# print(z2)

# 创建全1一维数组
o1 = np.ones(10)
# print(o1)

# 创建全1二维数组
o2 = np.ones((2,2))
# print(o2)

# 随机创建5个 0到1之间的一维数组
r1 = np.random.rand(5)
# print(r1)

# 随机创建5个 0到1之间的一维数组
r2 = np.random.random(5)
# print(r2)

# 随机创建2*2个 0到1之间的二维数组
r3 = np.random.random((2,2))
# print(r3)

# 随机获取一个从 1到10之间的整数
r4 = np.random.randint(1,10)
# print(r4)

# 随机获取两个从 1到10之间的整数
r5 = np.random.randint(1,10,2)
# print(r5)

# 类似range操作
r6 = np.arange(10)
# print(r6)

## 2、ndarray属性

In [49]:
# 维度
print(z2.ndim)

# 形状
print(z2.shape)

# 类型
print(z2.dtype)

2
(2, 2)
float64


## 3、ndarray类型

In [55]:
# 整形
arr3 = np.array([1,3,4],dtype=np.int)
# print(arr3)

# 浮点型
arr4 = np.array([1,3,4],dtype=np.float)
# print(arr4)

# 类型转换
arr5 = arr4.astype(np.int)
print(arr5)

[1 3 4]


## 4、数组运算

In [60]:
arr6 = np.array([[1,2,3],[3,4,5]])
# 加2
print(arr6+2)
# 相乘
print(arr6 * arr6)

[[3 4 5]
 [5 6 7]]
[[ 1  4  9]
 [ 9 16 25]]


## 5、索引和切片

### 5.1、一维数组
* 如果ndarray是一维数组，则与python列表切片功能相似

In [76]:
arr = np.arange(10)

# 索引0
# print(arr[0])

# 索引最后一个元素
# print(arr[-1])

# 切片 获取第一道第三个元素
# print(arr[0:3])

# 切片应该要注意，只是引用，因此修改数组元素，原有数组会进行更改
# arr_slice = arr[5:8]
# print(arr_slice)
# arr_slice[1] = 66
# print(arr_slice)
# print(arr)

# 采用copy
arr_slice1 = arr[5:8].copy()
print(arr_slice1)
arr_slice1[1] = 66
print(arr_slice1)
print(arr)

[5 6 7]
[ 5 66  7]
[0 1 2 3 4 5 6 7 8 9]


### 5.2、二维数组

In [90]:
# 构造3*3 二维数组
arr2 = np.random.randint(1,10,(3,3))
print(arr2)

# 打印第二行
# print(arr2[1])

# 打印第二行，第二列 写法一
# print(arr2[1][1])
# 打印第二行，第二列 写法二
# print(arr2[1,1])

# 切片操作，获取第一、二行数据
# print(arr2[:2])

# 获取所有行，第二列的全部数据
# print(arr2[:,1])

# 获取前两行，最后一列的数组
print(arr2[0:2,-1])

[[2 5 4]
 [8 6 8]
 [9 3 4]]
[4 8]


### 5.3、布尔索引

In [93]:
arr = np.random.randn(9)
print(arr)
# 打印大于0
print(arr[arr>0])

[-0.1622173   0.67579202 -1.44064737 -0.44373176 -0.34189905  0.49544518
 -2.47710611  1.40761469  0.64472034]
[0.67579202 0.49544518 1.40761469 0.64472034]


## 6、数组转置

In [106]:
# 转置成 3*5的二维数组
arr = np.arange(15).reshape((3,5))
# print(arr)

arr1 =  np.arange(4).reshape((2,2))
# print(arr1)
# 横轴转置 写法一
# print(arr1.T)
# 横轴转置 写法二
# print(arr1.transpose())
arrt = arr1.transpose()
print(arrt)

# 在二维数组中，axis=0 则是代表从上往下看 axis=1 则是代表从左往右看
print(arrt.transpose(1,0))

[[0 2]
 [1 3]]
[[0 1]
 [2 3]]
