# 二、numpy通用函数

In [1]:
import numpy as np

## 1、统计/数学相关函数

### 1.1、一元

In [32]:
arr = np.array([1,4,9],dtype=np.int)

# 开根号
print(np.sqrt(arr))

# 最大值
print(np.max(arr))

# 最小值
print(np.min(arr))

# 平均值
print(np.mean(arr))

# 方差
print(np.std(arr))

# 平方
print(np.square(arr))

# log2的对数
print(np.log2(arr))

# 求和
print(np.sum(arr))

[1. 2. 3.]
9
1
4.666666666666667
3.2998316455372216
[ 1 16 81]
[0.       2.       3.169925]
14


### 2.2、二元

In [26]:
arr1 = np.array([1,3,5])
arr2 = np.array([2,3,6])
# 同级元素的最大值
print(np.maximum(arr1,arr2))

# 同级元素的最小值
print(np.minimum(arr1,arr2))

# 数组相加 arr1+arr2
print(np.add(arr1,arr2))

# 相乘 arr1*arr2
print(np.multiply(arr1,arr2))

# 相减 arr1-arr2
print(np.subtract(arr1,arr2))

[2 3 6]
[1 3 5]
[ 3  6 11]
[ 2  9 30]
[-1  0 -1]


## 2、条件函数
* np.where(condition,x,y)

In [31]:
where_arr = np.random.randn(10)
print(where_arr)
print(np.where(where_arr>0,where_arr,0))

[ 0.92929288  0.94350171 -0.70339642  0.04832271  0.51471923 -0.13661988
  1.51514454  0.20044812 -0.30166657 -0.23347368]
[0.92929288 0.94350171 0.         0.04832271 0.51471923 0.
 1.51514454 0.20044812 0.         0.        ]


## 3、排序

In [44]:
# 一维排序
arr = np.random.randn(5)
print(arr)
arr.sort()
print(arr)

# 二维排序
arr1 = np.random.randn(3,3)
print(arr1)
# 按竖轴，从上到下排序
arr1.sort(0)
print(arr1)
# 按横轴，从左到右排序
arr1.sort(1)
print(arr1)

[-0.4737348   1.0063205   0.81824387  1.1709281   0.46363676]
[-0.4737348   0.46363676  0.81824387  1.0063205   1.1709281 ]
[[ 1.23762479  0.20940942  0.40630486]
 [-0.9023199   1.03499904  0.45561426]
 [ 0.31693064  0.60849118 -0.12577856]]
[[-0.9023199   0.20940942 -0.12577856]
 [ 0.31693064  0.60849118  0.40630486]
 [ 1.23762479  1.03499904  0.45561426]]
[[-0.9023199  -0.12577856  0.20940942]
 [ 0.31693064  0.40630486  0.60849118]
 [ 0.45561426  1.03499904  1.23762479]]


## 4、集合操作

In [47]:
arr = np.array([1,3,2,4,2,1])
arr1 =  np.array([2,3,5])

# 去重
print(np.unique(arr))

# 求差集
print(np.intersect1d(arr,arr1))

# 并集
print(np.union1d(arr,arr1))

[1 2 3 4]
[2 3]
[1 2 3 4 5]
